### ISSUE TITLE
Exilence Next Failed to login

### ISSUE THREAD

**Issue by nvrb4newnar** [viktorgullmark/exilence-next#879]
**Describe the bug**
Unable to login

**To Reproduce**
1. Open Exilence Next
2. Click on 'Log In with PathofExile.com'
3. Click 'Authorize' in browser
4. See error in Exilence Next (Request failed with status code 400)

**Expected behavior**
Successfully log in to Exilence Next using PoE account

**Screenshots**
![image](https://user-images.githubusercontent.com/63736102/230791558-ecc44bcc-3697-4b0d-912a-17760efad780.png)

**Version**
1.2.1

**Additional context**
Solutions tried but to no avail:
- Deleting %appdata%\Roaming\exilence-next-app
- Uninstalling and reinstalling Exilence Next

**Comment by nvrb4newnar** [comment]
Never mind, seems to be an issue on PoE servers. The issue has been fixed as the servers are back up.

**Comment by divenerapide** [comment]
Hi!
In patch 3.23 I had a problem with authorization in exilence next. After i opened link in browser (like in the screenshot above) and was redirected to poe website, and when I clicked on "Authorize" I had a message that the site is not confidential. And it doesn't solve after a few days. My screen is below, thanks.
![Screenshot 2023-12-12 041957](https://github.com/viktorgullmark/exilence-next/assets/93930457/6fb1029d-d5b6-4f37-a0dd-2d620caca08b)

**Comment by Jululu** [comment]
> Hi! In patch 3.23 I had a problem with authorization in exilence next. After i opened link in browser (like in the screenshot above) and was redirected to poe website, and when I clicked on "Authorize" I had a message that the site is not confidential. And it doesn't solve after a few days. My screen is below, thanks. ![Screenshot 2023-12-12 041957](https://private-user-images.githubusercontent.com/93930457/289724818-6fb1029d-d5b6-4f37-a0dd-2d620caca08b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzI5MzcsIm5iZiI6MTcwMjQ3MjYzNywicGF0aCI6Ii85MzkzMDQ1Ny8yODk3MjQ4MTgtNmZiMTAyOWQtZDViNi00ZjM3LWEwZGQtMmQ2MjBjYWNhMDhiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEzMDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGFmYjY2ZGI1ODRlMDI2YzFmOGMyMTVjYjk2NjA3OGEwYjFmNmYyYjI0OGMzYTQ3NzUyMGYwMmUzMTY3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hsC5kffiPYwiOwsQ7eA77SmnTkv0cD7P2vxa5jWlagk)

Same here!

**Comment by divenerapide** [comment]
ok guys, the problem is that the exilence next developer finish to work with app and off the servers.
 So, r.i.p, exilence next :C
